apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: api-demo # For new publications change the Product name
spec:
  name: "OperatedProduct 2" # For new publications change the Product CRD name
  systemName: api-demo # For new publications change the Product name
  backendUsages:
    api-demo-backend:
      path: /
  applicationPlans:
    plan01:
      name: "My Plan 01"
      setupFee: "00.10"   
  policies:
    - configuration:
        auth_type: user_key
        user_key: 3aeaac65b2ccb92f43c2e6856448612b
      enabled: true
      name: default_credentials
      version: builtin
    - configuration: {}
      enabled: true
      name: apicast
      version: builtin   
    - configuration:
        http_proxy: http://example.com
        https_proxy: https://example.com
      enabled: true
      name: camel
      version: builtin
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: "hit"
  methods:
    method01:
      friendlyName: Method01
  mappingRules:
    - httpMethod: GET
      pattern: "/"    
      increment: 1
      metricMethodRef: hits 
    - httpMethod: GET
      pattern: "/test"    
      increment: 1
      metricMethodRef: hits  
  # deployment:
  #   apicastHosted:
  #     authentication:
  #       oidc:
  #         issuerType: "keycloak"
  #         issuerEndpoint: "https://myclientid:myclientsecret@mykeycloack.example.com/auth/realms/myrealm"
  #         authenticationFlow:
  #           standardFlowEnabled: false
  #           implicitFlowEnabled: true
  #           serviceAccountsEnabled: true
  #           directAccessGrantsEnabled: true
  #         jwtClaimWithClientID: "azp"
  #         jwtClaimWithClientIDType: "plain" 